<?php
$PageTitle = "Father Frederick Crowe, S.J.";
include "header.php";
?>

<h1><?php echo $PageTitle; ?></h1>

<strong>As many who use the websites <a href="http://www.bernardlonergan.com">www.bernardlonergan.com</a> and <a href="http://www.lonerganresource.com">www.lonerganresource.com</a> know, Frederick Crowe died on Easter Sunday of this year. The following two paragraphs contain the obituary for Father Crowe written by Robert M. Doran, S.J., and link to the homily that Father Doran delivered at the funeral Mass on April 17 at Regis College, Toronto. The homily is accessible in <a href="pdf/frederick-crowe-homily.pdf">pdf</a> and <a href="audio/frederick-crowe-homily.mp3">mp3</a> format.</strong><br>
<br>

<img src="images/frederick-crowe.jpg" alt="Father Frederick Crowe, S.J." style="float: right; margin-left: 20px;">

Father Frederick E. Crowe died peacefully on Easter Sunday, April 8, 2012, at Ren&eacute; Goupil House, Province Infirmary, Pickering, Ontario, in his 97th year. Fred was born on July 5, 1915, in Jeffries Corner, New Brunswick, the son of Jeremiah Crowe and Margaret (Mahoney). He attended high school in Sussex, NB, and then received a Bachelor of Science degree in Electrical Engineering from the University of New Brunswick in 1934. He entered the Guelph novitiate on September 6, 1936. He studied philosophy at the Jesuit Seminary in Toronto from 1940 to 1943, and did his regency in Halifax from 1943 to 1946. He then returned to Toronto for his theological studies at the Jesuit Seminary (1946 to 1950). He was ordained a priest in Toronto on June 27, 1949. Following his tertianship year, he did a biennium in theology at the Gregorian University in Rome from 1951 to 1953, receiving his doctorate at the end of this period. He joined the faculty of the Jesuit Seminary in 1953 and taught there and at Regis College until he retired from teaching at age 65, becoming Professor Emeritus and devoting his energies full-time to research and writing. He became the first Director of the Lonergan Research Institute in 1985, and served in that capacity until 1992. From 1992 to 2006 he continued work at the LRI as one of the General Editors of the Collected Works of Bernard Lonergan and as author of numerous writings. He lived in the Regis Jesuit Community until 2006, and specifically at Pedro Arrupe House since 1983.<br>
<br>

Fred discovered his principal work during his years studying theology in Toronto in the late 1940s. For it was then that he became a student not only of theology but in particular of the work of Bernard Lonergan, who was on the faculty of the Jesuit Seminary at the time. When Fr Lonergan left Toronto for the Gregorian University in 1953, Fred assumed the task of preparing the index for <em>Insight</em>, a book that for all practical purposes was complete at the time, even if it was not published until 1957. Slowly he began the task of collecting the data on Lonergan's work. Fr Lonergan gave a number of his papers to Fred in 1953, and another set in 1972. These became the first installments on the Lonergan Archive, which was the basic research source in the Lonergan Center that Fred established at Regis College in 1970. But the Center contained much more: dissertations, articles, and books written on Lonergan or using his work, along with audio recordings of lectures by Lonergan. In 1985 the Center grew into the Lonergan Research Institute. Fred oversaw the establishment of this distinct institution and was its Director in the early years of its existence. In 1986 Fred signed a contract with University of Toronto Press for the publication of the Collected Works of Bernard Lonergan, a project for which he served as General Editor together with Robert Doran. He will always be remembered as the foremost Lonergan scholar of the twentieth century and as the person without whom Lonergan's work would never have become as accessible as it is. There will be a large international community forever grateful to him for what he did to make the Lonergan legacy possible. But his work is not limited to promoting the writings of his great teacher. His list of publications in his own name comes to roughly 200 items, including both books and articles. His work involved in teaching Trinitarian theology is legendary. Some of his writings are landmark interpretations of Lonergan's work, but some are original contributions, including a few that will achieve status as permanent advances in systematic theology. Among the latter is the work he did interpreting and advancing Lonergan's later thought regarding the Christian approach to world religions. He also owns the distinct achievement of having published an original book at the age of 90, <em>Christ and History: The Christology of Bernard Lonergan from 1935 to 1982</em>. This book is an indispensable guide to the development of Lonergan's thought on Christology.

<?php include "footer.php"; ?>